### ISSUE TITLE
食谱不够丰富建议加大力度

### ISSUE THREAD

**Issue by kexue-z** [KafCoppelia/nonebot_plugin_what2eat#1]
至少来个几千种吧(😋

**Comment by KafCoppelia** [comment]
草这你得问你的群友吧……
欢迎pr美食列表🍕🍔🍟🌭🍿🧂🥓🥚🍳🧇🥞🧈🍞🥐🥨🥯

**Comment by kexue-z** [comment]
你就是群友 快多写写, 实在不行可以去爬点😋
最好是方便快捷还能有食谱的
进行中餐西餐各菜系进行分类

**Comment by BalconyJH** [comment]
good first issue 👍

**Comment by kexue-z** [comment]
https://github.com/Anduin2017/HowToCook

请

**Comment by KafCoppelia** [comment]
[v0.2.4](https://github.com/KafCoppelia/nonebot_plugin_what2eat/releases/tag/v0.2.4)

**Comment by kexue-z** [comment]
“怎么才这点啊”

**Comment by KafCoppelia** [comment]
你要那么多干啥啊，群友都吃的完？

**Comment by kexue-z** [comment]
哼（村民）
