### ISSUE TITLE
报错ModuleNotFoundError: NO module named 'nonebot.adapters.onebot.exception'

### ISSUE THREAD

**Issue by krasus1995** [KafCoppelia/nonebot_plugin_what2eat#12]
![E{8{JWS Y4O9E@SBPF_IS1A](https://user-images.githubusercontent.com/97447697/179913858-eaf635e4-b225-49d6-90fb-d1d9510af635.png)

**Comment by KafCoppelia** [comment]
这个是插件依赖没约束好，我铁锅。改`data_source.py` Line 2：
```
from nonebot.adapters.onebot.v11.exception import ActionFailed
```
我会在下个版本中修复此约束。

**Comment by KafCoppelia** [comment]
[v0.3.3](https://github.com/MinatoAquaCrews/nonebot_plugin_what2eat/releases/tag/v0.3.3)已修复此问题
