### ISSUE TITLE
想问一下群号的格式，按照readme的格式写了之后报错

### ISSUE THREAD

**Issue by Astolfocat** [KafCoppelia/nonebot_plugin_what2eat#2]
在.env.{environment}文件中设置如下：
GROUPS_ID=["123456789"]
报错：
 if len(self._data["group_food"][group_id]) > 0:
KeyError: '123456789'

**Comment by KafCoppelia** [comment]
代码已优化，[v0.2.3](https://github.com/KafCoppelia/nonebot_plugin_what2eat/releases/tag/v0.2.3)

**Comment by KafCoppelia** [comment]
若有问题请reopen this issue
