### ISSUE TITLE
[Bug]询问今天吃什么出现KeyError

### ISSUE THREAD

**Issue by OnlyblackTea** [KafCoppelia/nonebot_plugin_what2eat#26]
如图，可以复现。
![error](https://user-images.githubusercontent.com/38585636/210077008-7e549eaa-24d4-418a-b012-77608949f672.png)

**Comment by OnlyblackTea** [comment]
重启了几次以后好了

**Comment by KafCoppelia** [comment]
貌似是不是开了`USE_PRESET_MEU`但是下载失败导致的，多次重启某次下载菜单成功就没事了？

**Comment by OnlyblackTea** [comment]
> 貌似是不是开了`USE_PRESET_MEU`但是下载失败导致的，多次重启某次下载菜单成功就没事了？

我用的是默认设置，看起来应该是这样……
不知道怎么让nonebot走proxy呢

**Comment by KafCoppelia** [comment]
看nb2手册，有写
