### ISSUE TITLE
全局配置里的群组提醒一旦加上无法通过修改全局配置关闭，只能修改文件 `resource/greetings.json` ？

### ISSUE THREAD

**Issue by gagadaxiao** [KafCoppelia/nonebot_plugin_what2eat#36]
就是这一配置 GREETING_GROUPS_ID=["123456789", "987654321"]   # 默认开启小助手的群组，或{"123456789", "987654321"}

加了群号运行一次之后，注释掉或者清空群号还是会每个时间段提醒。`greetings.json` 里记录为(示例)
```
"groups_id": {
    "123456789": true,
    "": true
```

**Comment by KafCoppelia** [comment]
确实大意了，本意是 `GREETING_GROUPS_ID` 配置常开的群组，没想到用户如果去掉了 `greetings.json` 也没有同步更新移除。感兴趣的话，你可以提pr
😉

**Comment by gagadaxiao** [comment]
并不会改..只是使用

**Comment by KafCoppelia** [comment]
想了一下，这个功能其实不好实现。用户如果在 `GREETING_GROUPS_ID` 移除了群聊ID， `greetings.json` 同步移除，这样要求插件去记录上次的 `GREETING_GROUPS_ID`，并且每次去比较，需要额外多一个 `key-value` 去保存。最好是拿命令去关闭好了。

此外，这个 `groups_id` 的键值对数据应该不和其余问候语数据放在一个json里（我其实后续想对此进行修改），因此这块目前不想改动
