### ISSUE TITLE
群聊之间菜单貌似互通的bug

### ISSUE THREAD

**Issue by snowykami** [KafCoppelia/nonebot_plugin_what2eat#4]
比如在群A添加了群特色菜品
在群B就会显示菜品已添加

**Comment by KafCoppelia** [comment]
这么先进的吗？图来

**Comment by KurohaneKaoruko** [comment]
```
for group_id in self._data["group_food"]:
    for food in self._data["group_food"][group_id]:
        if food == _food_:
            return 2
```
utils.py文件下的food_exists()的该段，似乎对每个群特色菜单都判断了一遍是否存在
从而导致了在某一个群添加的特色菜单，在另一个群尝试添加时会提示已添加，但菜单里却没有。

**Comment by KafCoppelia** [comment]
dev版[v0.3.0a2](https://github.com/MinatoAquaCrews/nonebot_plugin_what2eat/releases/tag/v0.3.0a2)作出修复，目前不确保版本稳定

**Comment by KafCoppelia** [comment]
[v0.3.0](https://github.com/MinatoAquaCrews/nonebot_plugin_what2eat/releases/tag/v0.3.0)

**Comment by KafCoppelia** [comment]
按理是没有问题了，如果仍存在请reopen
