### ISSUE TITLE
正则指令无回复

### ISSUE THREAD

**Issue by gensofubi** [KafCoppelia/nonebot_plugin_what2eat#45]
今天吃什么指令无回复，同#41.已尝试切换到v-0.4.x和切换到较早commit，无效果。
顺便问下图片资源在哪里下载

**Comment by KafCoppelia** [comment]
没有图片资源

其次，最近一次有时间根据上游nb做出适配的时间在国庆假期吧……

**Comment by gensofubi** [comment]
问题解决了，用的onebot adapter的MessageEvent所以本地console测试无响应，部署后使用RegexStr的版本是没问题的
