### ISSUE TITLE
能在建议后边添加配图吗？

### ISSUE THREAD

**Issue by huihuiismywife** [KafCoppelia/nonebot_plugin_what2eat#5]
如图，有些东西可能因为地方原因吧没有听过（流泪猫猫头.jpg），想加个配图辅助一下（ps：绝对不是想半夜放毒）
就像是说像这样的
![图片](https://user-images.githubusercontent.com/107234845/173195716-b8c6ee44-9f85-4320-9709-2b5cefa6f6e4.png)

主要是想问能不能自己设置图片啊，从本地选择什么的

**Comment by KafCoppelia** [comment]
好，有时间改改

**Comment by KafCoppelia** [comment]
目前重构代码，[v0.3.0a2](https://github.com/MinatoAquaCrews/nonebot_plugin_what2eat/releases/tag/v0.3.0a2)，有关文字和图片的数据储存比较头疼，要重新考虑数据储存方式，先把`v0.3.0`稳定下来后再添加新特性

**Comment by KafCoppelia** [comment]
[v0.3.4a1](https://github.com/MinatoAquaCrews/nonebot_plugin_what2eat/releases/tag/v0.3.4a1)实验性地添加了此项功能，目前是测试版，不确保功能稳定。如果想尝试，安装时请指定版本号。

另外，惠惠是我老婆

**Comment by huihuiismywife** [comment]
谢谢大佬
另外，拔刀吧（无慈悲）

**Comment by KafCoppelia** [comment]
[v0.3.4](https://github.com/MinatoAquaCrews/nonebot_plugin_what2eat/releases/tag/v0.3.4)已发布
